name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - run: dotnet restore MineWatch.sln

      - run: dotnet format MineWatch.sln --verify-no-changes --no-restore

      - run: dotnet build MineWatch.sln --no-restore

      - run: dotnet test MineWatch.sln --no-build
